Milestone 4 Book store project
imhilla/Bookstore pull request #5
Opened 2020-10-23 05:29 UTC by imhilla

Hello TSE, 
Please review my fourth milestone project of the redux react section.
Thank you,
Hillary

2020-10-23 08:54 UTC, mosaaleb requested changes
### Changes required

Well done @imhilla :clap:. Most of the requirements are handled, yet we have some work to do before moving on.


- [ ] Add a short summary about this pull request in the description.
![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)

- [ ] Let's start working on the Readme file.
![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png)


Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2020-10-23 08:54 UTC, mosaaleb commented on src/reducers/filter.js
> +const filter = initialState => (state = initialState, action) => {
- [ ] Why disabling these eslint rules? I think we don't need it.

2020-10-23 19:14 UTC, bellom requested changes
## Hi @imhilla   :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-10-23 19:14 UTC, bellom commented on src/reducers/books.js
>  /* eslint-disable react/prefer-stateless-function */
we are indirectly changing the rules by disabling these rules, let's fix the codebase instead.

2020-10-23 19:14 UTC, bellom commented on src/containers/booksform.js
> +              {/* eslint-disable-next-line no-return-assign */}
we are indirectly changing the rules by disabling these rules, let's fix the codebase instead.

2020-10-23 19:14 UTC, bellom commented on src/containers/booksform.js
>        // eslint-disable-next-line no-return-assign
we are indirectly changing the rules by disabling these rules, let's fix the codebase instead.

2020-10-23 19:14 UTC, bellom commented on src/containers/booklist.js
> +  books: PropTypes.arrayOf(PropTypes.any),
According to the previous @mosaaleb told you to use `props-types.shape`

Using [PropTypes.shape](https://dev.to/cesareferrari/how-to-specify-the-shape-of-an-object-with-proptypes-3c56) here will allow you to set a type check that is more accurate, then you can remove the inline comment to disable prop-types.

2020-10-23 19:14 UTC, bellom commented on src/containers/booksform.js
> +                // eslint-disable-next-line react/destructuring-assignment
we are indirectly changing the rules by disabling these rules, let's fix the codebase instead.

2020-10-25 16:03 UTC, mosaaleb requested changes
#### Changes Required

Thanks for working on the prevoius reviews requirements. Still I got this error when I tried to add multiple books.


![Screenshot from 2020-10-25 17-57-02](https://user-images.githubusercontent.com/4246637/97112292-1f690000-16ec-11eb-9017-b1a590f94422.png)


It seems that that given `id` for the new books are the same. Please fix this issue and submit a new code review.


###### Muhammad Ebeid

2020-10-25 18:28 UTC, jofer86 approved these changes
## `const PROJECT_STATUS = "APPROVED"` 🚀 🚀 🚀 
## :wave: :wave: Hello! I'm Jorge, and  I will be conducting this code review. Let me get a closer look 🔎 🔍 🔎 🔍 🕵🏼 

- All of the required changes were taken care of. Great Job!!!! you might move along.

--------------------------------------------------------------------
**Rock on**  🤘🏼 
**_Jorge Fernando Rincón Figueroa._** 
Technical Support Engineer.

2020-10-26 03:55 UTC, merged