Milestone 5 Book store
imhilla/Bookstore pull request #6
Opened 2020-10-23 15:33 UTC by imhilla

Hi TSE,
Please review my capstone project for the react and redux section. This is the last milestone.
I added styling to the project.
I added a descriptive readme section.
I added a progress bar, and chapters section.
Thank you
Hillary

2020-10-23 18:45 UTC, Forison requested changes
## Status:: Changes Required✖️.
# 🙋‍♂️ Hillary
#### You have done a good job on this one so far, your design looks like the original page. However, there are a few changes we have to make to get this project approved🤗.
> Please not that this is the fifth milestone you still have one more milestone to go.
* [ ] Do not make changes to linter configs, check my comment below👇.
* [ ] File not related should not be push to the repo, but rather put their paths in gitignore so they don't get committed. Kindly remove the `debug.log` from repo
* [ ]  The category field should take the value of the selection not being stack on the "choose category". Currently "Choose category does not change even when a new category is selected".
### That is it, kindly make the changes and submit a re-review👨‍🔧.
#### Happy coding👨‍💻
Addo Forison

2020-10-23 18:45 UTC, Forison commented on src/components/categoryFilter.js
> +  // eslint-disable-next-line no-return-assign
- Do not disable eslint

2020-10-23 18:45 UTC, Forison commented on src/containers/booklist.js
>              // eslint-disable-next-line react/jsx-props-no-spreading
- Do not disable eslint

2020-10-23 18:45 UTC, Forison commented on src/containers/booksform.js
> +                // eslint-disable-next-line react/destructuring-assignment
- Do not disable eslint

2020-10-23 18:45 UTC, Forison commented on src/reducers/books.js
>  /* eslint-disable react/no-unused-state */
- Do not disable eslint

2020-10-25 17:43 UTC, shloch approved these changes
## Hello @imhilla , 

Perfect execution, the design clone is very very close.
![bokstore](https://user-images.githubusercontent.com/40712459/97114618-e0d64400-16f1-11eb-99f6-0289d4b3e599.gif)

You get a thumbs up for this. Nothing much to add to the great job.
We ready for next milestone.
Happy coding

2020-10-26 03:55 UTC, merged